var grog_of_substantial_whimsey_table = [
	"PC suddenly remembers that they've been lying about who they are the whole time, and are actually someone else entirely.",
	"PC becomes a reusable spell component. (any semi-competent mage will be able to notice this)",
	"PC can Wish the death of one being, but will also die.",
	"PC can access their brain by unscrewing the top of their skull.",
	"PC's mouth lets out light, illuminating 5 ft. in front of the PC whenever it's open.",
	"PC is unknowingly inducted into a secret society.",
	"PC can speak with domestic fowl, but they tend to lie to the PC.",
	"PC sees dead people who bother them a lot.",
	"The PC, and the PC’s party learns the 5 minute ritual to summon the PC. (Just a pentagram, nothing fancy)",
	"Roll again, effect behaves like an STD.",
	"PC can summon a demon, but only has a 10% chance of controlling it. (Demons notoriously hate anyone who summons them)",
	"PC can resurrect another creature once per year.",
	"The tip of the PC's thumb can be lit harmlessly like a candle.",
	"PC becomes a dragon in a human form with the same stats as they had before, but has forgotten how to polymorph.",
	"Roll again, the effect is twice as strong. (Twice as fast, twice as much, etc.)",
	"PC can concentrate to have background music play for them. (DC 15) concentration, 1d20 rounds.",
	"PC thinks magic is actually impossible, and won't accept it. Refers to it as 'witchcraft' and 'nonsense'",
	"PC loses 1d2 feet in height, their clothes & armor amazingly still fit.",
	"PC is now much more comfortable around the (un)dead than the living.",
	"Any casted magic that affects the PC causes them to be soaked in lamp oil.",
	"The next sword that hits the PC receives a permanent +1 bonus.",
	"PC can no longer kill anything.",
	"PC’s middle name becomes “Wonder Noodle” and must always say their full name when asked.",
	"When PC is angry, their hair erupts into a harmless flame.",
	"PC gains a grog addiction, if they don't consume one once per week, they take -1 to all ability scores, increasing by one each day without grog.",
	"PC can exist comfortably in harsh environments for 10 minutes/day",
	"Every week, the PC must sacrifice an enemy or gain a -1 penalty to all ability scores and saves, increasing by 1 every day that an enemy isn't sacrificed. A special sacrificial dagger appears in the PC's inventory and cannot be used for anything but a killing blow. It is also bound to the PC.",
	"At the start of every encounter the PC must succeed a DC 10 Will save or roll for a new alignment.",
	"PC’s organs will never fail, even if removed.",
	"Roll again, the next living thing the PC touches also receives the affect.",
	"PC's dream semi-manifest in reality. (Like warped trees, or obscurely built buildings. At DMs discretion)",
	"PC gains Thaumaphilia, an intense fascination with magic.",
	"Flowers grow out of the spots where the PC walks.",
	"PC seemingly ‘walks on air’ and is permanently 5 inches above all solid surfaces.",
	"PC becomes pregnant. Does not matter what sex, if any, the PC is. 01-49% = boy, 50-98% girl, 99-100% other. Will be a clone of the PC & a normal nine month pregnancy. Morning sickness & other symptoms apply as DM sees fit.",
	"One of the PC's permanent effects or injuries are cured! If they don't have one, re-roll for one.",
	"PC's bones turn to wood, and can live off sunlight. When they go up an age group, they go up a size category as well as receiving the penalties of aging.",
	"PC gains wonderful plumage.",
	"PC becomes so good at flexing, they will rip through whatever clothing and/or armor they're wearing making it worthless unless they get it repaired.",
	"PC’s body becomes an orangutan. (no stat change)",
	"PC forgets a random language.",
	"PC realizes the meaning of life, but is unable to tell anyone else. They are also hunted by cults (and maybe gods) who want to know.",
	"PC sprouts a tree on their head. Extends lifespan x5000. Tree will grow until too heavy for person, enveloping them and taking root. Person will become immobile tree. Retains personality and speech.",
	"Lung capacity enlarges harmlessly. Can hold breath for 20 minutes.",
	"PC is owed 1 favor by a random god.",
	"PC thinks 'They' are after them. Whoever 'They' are.",
	"PC's face has the same properties as catnip. (A cat allergy may be included at DMs discretion)",
	"Arcane markings (Explosive Runes) appear on skin permanently, cannot be removed even if the skin is.",
	"PC falls madly in love with random party member. DC 25 to get over themselves, can only make save 1/month.",
	"PC’s dreams are replaced with visions of drinking a particular drink in a particular tavern.",
	"PC becomes aware of how to process opiates and meth.",
	"PC's stomach now functions similarly to a bag of holding.",
	"When the PC is asleep, their consciousness leaves their body in the shape of their favourite mundane animal to fuddle about.",
	"PC's shadow does not do the same thing as the PC. It is the same size, and does not leave no matter what time of day.",
	"PC is haunted by nightmares of a lost island that holds extraordinary improbable animals.",
	"PC gains an imaginary friend who tells them to kill everyone they meet.",
	"PC can bathe in moonlight, and is squeaky clean the morning after.",
	"If the PC punches an ally, they forget who the PC is.",
	"PC switches ears with the next race they come into contact with. (Ears will shrink/grow proportionally for all involved)",
	"The PC becomes either an herbivore or a carnivore. (50% chance of either. Any food of the other kind will induce vomiting)",
	"PC can easily climb trees like a cat, or a monkey.",
	"PC develops Thaumaphobia, an intense fear of magic.",
	"PC can chop non-magical wood with their bare hands.",
	"PC's age fluctuates ± 10 years each day.",
	"PC's breath is a light flurry of snow.",
	"PC cannot exit through the same way they entered.",
	"Whenever the PCs rolls a 20 on a 1d20, they are compelled to shout “[PC’s name] strikes again!”",
	"PC lays an egg (regardless of sex). (What kind is DMs choice.)",
	"PC no longer gives off any indication that they are alive (or undead). Is not detected by detect life or detect undead.",
	"PC learns to understand the next language they hear that they don’t currently know.",
	"If the PC hears their name, they petrify for 2d4 rounds.",
	"PC's presence causes holy symbols to glow red. Including mundane ones.",
	"When the PC is teleported, they cannot take any gear (clothing and equipment) with them.",
	"When it’s cold, the PC can cut glass with their nipples.",
	"PC’s presence makes jumping carp violent.",
	"Fireflies swarm the PC at night, and does not gain bonus for hiding in darkness. (No penalties either)",
	"PC cannot enter a room without announcing their presence",
	"PC remembers the night a wizard plucked them from the pumpkin patch, and turned them into what they are now.",
	"PC becomes soluble in rainfall. (Drinking liquids is harmless)",
	"PC now owes their life to someone who won’t be born for centuries.",
	"PC sprouts a 3 ft prehensile monkey tail.",
	"PC cannot perform any action without announcing their name.",
	"PC does not age while asleep. Increase lifespan by 1/3.",
	"PC teleports 1 mile; stone replica appears in his place.",
	"Roll again, the effect is twice as strong. (Twice as long, twice as much, etc.)",
	"PC's clothes change randomly when attacked. (Armour is not affected)",
	"PC's breath becomes combustible.",
	"Last creature killed by PC is reanimated, and hunts the PC.",
	"PC becomes aware that at death, they are resurrected with opposite alignment.",
	"PC becomes very talented at making whittled spoons.",
	"PC realizes that the universe was born in a huge explosion. Is allowed to start religion.",
	"PC can juggle anything they can lift.",
	"PC becomes addicted to casting the last spell they casted, and really enjoys casting it whenever they get the chance, or an excuse.",
	"PC cannot enter a building without being invited.",
	"Deludes PC into believing the grog functions as indicated by a second die roll (no save).",
	"PC no longer has muscles. (But can do everything without them.)",
	"Everyday when the PC enters combat, PC's sweat becomes a minor water elemental. 3d6 rounds, 50% chance of being hostile. Dissipates at midnight.",
	"Any liquid consumed now produces the effect of the grog to the PC.",
	"PC violently erupts into flames, burning off all of the hair on their body. Any hair that grows back is now fireproof.",
	"PC suddenly recalls a past life where they were a destitute beggar who died, with no one to miss them.",
	"PC teleports to where they had visited 24 hours ago.",
	"PC's touch brings wilting flowers back to life.",
	"PC can cast Detect Stupid at will. (doing so might only detect the PC)",
	"PC can become a mount.",
	"PC becomes a dehydrated water salesmen. (just add water!) (3 sp per can)",
	"PC grows cat ears, and gains a dislike of water. PC also likes fish.",
	"Whenever the PC is struck with magic, the surrounding 50 ft area shifts as though it were the opposite time of day. (actual time does not change)",
	"PC can expel bodily gasses as a free action from the pores of their skin, and conceal themselves within their 5 ft. square. No effect on any adjacent squares.",
	"PC can explode at will, reducing HP to 0. Explosion deals 1 point of damage per hit point in a 20 ft. area. Each time reduces max HP by 2 and disintegrates any non magical possessions including armour and weapons.",
	"Roll again, effect can be brewed into a magical potion. (Ingredients are DMs choice)",
	"Moonlight makes the PC look like a decomposing corpse.",
	"PC's sneeze is now a strong gust of wind.",
	"To PC, 'Something pulls at your heartstrings, you feel as though you need to give the next person you see all of your money.'",
	"PC's next temporary effect (other than the grog) becomes permanent (and cannot be removed).",
	"Roll again, the effect is twice as strong. (Twice as fast, twice as much, etc.)",
	"PC sprouts a singing venus fly trap on their shoulder that sings when the PC is happy.",
	"If the PC stares at someone, they are unable to look away.",
	"PC gains a valve that has a coin slot attached to it. The PC can insert the valve anywhere, deposit the number of gp for a grog, and it will dispense it!",
	"Doors that the PC opens sigh.",
	"Whenever the PC is affected by any sort of magic, the fabled land-shark learns their current location.",
	"PC gains memories of a past life of an insanely powerful epic wizard. Specifically when that epic wizard went to the future to (kill, maim, higher, talk to, have fun with, give an item to, warn, perform an action around, or spite) his future life (the PC) the next day.",
	"A women walks up to the PC, and proclaims that she is the PC's wife. (Children at DM's discretion.)",
	"Whenever the PC sings, a wave expels out and fills the immediate 10 ft area with blossoming flowers, regardless of the PC's singing ability.",
	"PC agrees with everything, even if it doesn't make sense, or is contradictory. PC’s personal beliefs are unaffected.",
	"PC gains a grog addiction, if they don't consume one once per week, they take -1 to all ability scores, increasing by one each day without grog.",
	"The PC slowly, painlessly, and inconveniently turns to stone from the fingers and toes inwards. 1 limb per minute turn to stone. Can be removed by a remove curse. (Or reversed with a stone to flesh.)",
	"The PC suddenly becomes aware of a nearby dragon treasure horde, the only problem is that the dragon knows that the PC knows.",
	"PC gains once per day use of a spell equal to Cha modifier. (Use modifier for DC)",
	"PC gains another personality that presents itself when the PC sleeps. (roll for alignment of other personality.)",
	"Roll again, the next living thing the PC touches also receives the affect.",
	"PC becomes a were-farmer.",
	"PC grows a beard, 2 ft long, permanent. If it's removed in anyway, it grows back overnight.",
	"PC naturally attracts bears, 60% chance of being friendly, but will not fight for him.",
	"PC attracts floating animated hands. (Tend to steal possessions and hold them)",
	"PC gains a halo, and will be revealed with a detect good spell, regardless of alignment or true nature.",
	"PC attracts the undead and it's necromancers, friendly or not. (Usually not)",
	"PC becomes an animated object version of themselves. (Takes damage normally)",
	"PC suddenly remembers where they had buried their treasure chest full of doubloons.",
	"PC realizes the exact location of a particular flower that becomes the PC's newest obsession. (The flower can be magical or not.)",
	"PC’s body becomes a medium sized infernal imp. (no stat or alignment change)",
	"PC cries at the sight of flying birds, because it's such a beautiful metaphor for their soul.",
	"PC loses all secondary sexual characteristics of their race.",
	"Whenever the PC is alone, they painfully transform into an strange bird-like thing. The PC instantaneously reverts to normal if another person or creature goes near them or sees them.",
	"PC slowly remembers their time at war each night, and is forthcoming about telling old war stories at the campfire.",
	"PC’s esophagus can function as a scabbard that wouldn’t prevent movement, eating, talking, or breathing.",
	"PC's mouth becomes a set of 4 tentacles 2 ft long.",
	"PC has an intense need to narrate his actions/feelings and surroundings.",
	"PC can communicate feelings through physical contact.",
	"PC becomes a compulsive skinny dipper. Any water they swim in is treated as holy. (or evil, depending on alignment)",
	"PC’s dreams are replaced with visions of killing someone they haven’t met yet.",
	"PC becomes aware of a mundane object of his choice, and will only ever be comfortable with the object being around.",
	"Whenever the PC falls more than 20 ft. they make a 6 foot whole in the ground in the shape of their body when they land. Falling damage applies normally.",
	"Whenever the PC hears the laughter of children, they painfully transform into a troll, and revert when they’re struck.",
	"PC knows the birthday of anyone they touch.",
	"PC is haunted by the ghost of their childhood Saber Toothed Lolrus.",
	"Roses replace the PC's hair. They grow at the normal rate of hair, and blossom when in season, giving the PC a temporary +1 to CHA.",
	"Any fires set by the PC attract the undead like moths to a flame, whether they're friendly or not. (10% of being friendly)",
	"PC grows a hairy tail, 3 ft long. Objects smaller than the PC’s hand can be stored in the tail.",
	"PC appears to be an old black and white cartoon.",
	"Roll again, and the PC remembers that they’ve had the effect the whole time.",
	"PC experiences acute paranoia whenever they hear their name.",
	"Whenever someone first strikes the PC, both them and the attacker rotate 180 degrees in the direction they’re facing, and are both considered flat-footed the first time it happens.",
	"PC finds a kitten in their pocket. The PC falls instantly in love with the kitten as though under a charm effect, no saves. Anyone who sees the kitten is distracted for 1d4 rounds, even if they've seen the kitten before. Afterwards, they make a DC 13 fortitude save or be distracted for another 1d4 rounds.",
	"PC has eyes in the back of their head. Can only use one of their pairs of their eyes at a time.",
	"PC apologizes profusely every time they attack and/or kill something. Will otherwise feel the same way about fighting as before the effect.",
	"PC gains lycanthropy. (Were-wolf)",
	"For the next 1d6 weeks, every time the PC removes any head gear, a large white rabbit appears from underneath it. It is a normal rabbit. 01-50% Male, 51-100% Female. They will mate and produce offspring normally.",
	"PC lays an egg (regardless of sex). (What kind is DMs choice.)",
	"PC's only mode of transportation is the moon walk.",
	"PC learns to understand the next language they hear that they don’t currently know.",
	"PC becomes severely prejudice against kobolds.",
	"PC gains a birthmark of nobility from a distant or made up country.",
	"PC naturally attracts dire animals (DMs choice each time.) 50% of being friendly.",
	"PC doesn’t stick to spider’s web. They can attempt to pluck spider’s webs.",
	"PC can mesmerize non-magical animals they can see by dancing.",
	"PC's mouth no longer opens when they talk, but words and sounds still come out as normal.",
	"PC becomes addicted to the last substance they consumed before the grog.",
	"PC remembers the night a wizard killed them. It’s a little fuzzy why and how they’re alive now.",
	"PC compulsively swears whenever they pay anyone or anything a compliment.",
	"PC realizes they’re an escaped slave whose owner is tracking them.",
	"PC is transformed into one the last surviving member of an endangered species. (That strangely enough has the exact same characteristics as the race they were beforehand, other than appearance)",
	"PC hears 1d4 voices in their head from now on.",
	"PC grows another set of arms just beneath their normal ones.",
	"PC does not have a reflection.",
	"Roll again, the effect is twice as strong. (Twice as long, twice as much, etc.)",
	"A hat appears on the PC's head. If it is removed, another hat appears under it. There can never be a point where the PC is not wearing a hat. Each hat can be sold for 3 cp.",
	"PC's finger nails dispense magical ink, and can be used to scribe spells with.",
	"Roll 1d12, at that time of day, the PC emits a powerful beam of light that has no effect other than alerting absolutely everything that can see it to your presence at that moment.",
	"PC gains a D20 of Destiny, which the PC can consult at-will in-game.",
	"PC becomes very talented at tomfoolery.",
	"PC is able to summon an extra-dimensional kitchen to prepare any type of fancy food they want.",
	"PC can balance on anything when they are completely naked. If touched with anything (including rain) the effect is negated.",
	"Any object that's less than 1 pound within 10 ft of the PC begins to orbit around them. When the PC moves more than 10 ft away from the original spot of the object, they stop and return to where they were.",
	"PC hiccups butterflies. 2d4 butterflies per round for 2d4 rounds when caught flat-footed (or surprised).",
	"The PC’s feet cannot smell, and gets occasionally complimented for it regardless of the situation. NPCs are unaware of any compliments they give.",
	"PC is able to kill stones with birds.",
	"Any food the PC cooks is able to speak.",
	"Any liquid consumed now produces the effect of the grog to the PC.",
	"PC's brain is bombarded by stupidity. After 1d2 days of recovery, they can tell terrible jokes as a swift action, and causes sentient creatures to make a DC 17 will save or be stuck 1d4/level rounds pondering how dumb it is. Creatures are considered staggered.",
	"PC suddenly recalls all of the circus training they received as a circus elephant in a past life.",
	"Everytime PC snaps their fingers, a biscuit appears before them. It's a normal biscuit. Max 1d4/lvl biscuits per day.",
	"PC grows an afro that can be used as a backpack.",
	"PC cannot become non-magically dirty.",
	"PC's presence boils any kind of eggs if within 30 ft, no matter what. (stay away from hens)",
	"PC's hands and forearms are immune to acid.",
	"PC can make a DC 23 will save to grow mustache out of sheer force of will.",
	"PC's neck, arms, and legs become incorporeal, but their head, hands, feet and body do not.",
	"PC becomes easily mistakable for a regional political revolutionary.",
	"PC no longer has weight. Automatically fails bull rush and trip saves. Is otherwise unaffected. (i.e. falling damage, load carried.)",
	"Roll again, effect can be synthesized into a poison. (Ingredients are DMs choice)",
	"Next profanity used by PC becomes a living, vile entity.",
	"PC believes anything shiny can be used as money.",
	"PC's skull becomes diamond. (does not affect their ability to live or grow)",
	"PC is allergic to magical creatures.",
	"Roll again, the effect is twice as strong. (Twice as fast, twice as much, etc.)",
	"PC's skin is burned by moonlight. 1d4 dmg/round",
	"PC naturally attracts deinonychus' (raptors). 40% chance of being hungry.",
	"PC is always right about the best choice for the interior decor of any room.",
	"PC cannot be killed with rope.",
	"Any casted magic that affects the PC causes an extremely blasphemous tattoo to appear.",
	"PC's soul can leave their body and haunt any inanimate objects (weapons, lamps), but is fatigued when they return to their body.",
	"PC is nourished by grass instead of food. (All other foods make them vomit.)",
	"With exception to the eyes and brain, the PC begins to harmlessly decompose. (Is not undead, no longer eats)",
	"PC can shoot any thin elongated object as arrows. PC takes a -4 to attack bonus when using them.",
	"PC gains a grog addiction, if they don't consume one once per week, they take -1 to all ability scores, increasing by one each day without grog.",
	"PC’s body parts are replaced with fake ones. (PC has an urge to go find their original body)",
	"PC can summon the undead. 40% chance of controlling it. Anything summoned disappears at midnight.",
	"PC receives a participation trophy, with “You Tried” engraved on it.",
	"PC's heart becomes clockwork. It must be wound every 24 hours or else it stops. If it stops, PC's hit points drop to -1, and are restored to full if it's rewound. PC's eyes become removable pearls, retain normal sight.",
	"Roll again, the next living thing the PC touches also receives the affect.",
	"PC's hair becomes a very large powdered white wig. PC also gains a gavel.",
	"PC teleports 1d20 years into the past, in the same spot. The same amount of years later, they walk into the bar and watch themselves disappear.",
	"PC enjoys a good game of chess with only mirrors as his opponent.",
	"Everyone no longer can take the PC seriously.",
	"The only male name the PC is able to pronounce is Gary.",
	"PC's touch can drain 1d8 hit points, but is drained the same amount.",
	"PC is awake and alert the instant they wake up, regardless of how many hours they slept. Can also never be hungover.",
	"PC suddenly remembers they really, REALLY needed to do something, but for the life of them cannot remember what it was.",
	"PC now tends to distantly stare at other PC's unmentionables quite blatantly.",
	"PC’s body becomes a panda. (no stat change)",
	"PC is compelled to devour kobolds on sight.",
	"PC constantly sounds like a grandma, using the terms 'pooky' and 'schnookums' regardless of the situation. PC pinches cheeks too.",
	"Once per day, the PC can transform a segment of wall into a door.",
	"Within 5 ft of the PC is always 10 degrees colder.",
	"PC is now continuously tempted by demons in their sleep.",
	"PC will become addicted to the next substance they consume.",
	"PC becomes a were-saxophone player.",
	"PC gains devil horns, and will be revealed with a detect evil spell, regardless of alignment or true nature.",
	"PC gains fangs, but not a bite attack. Meat is more enjoyable now.",
	"PC’s dreams are replaced with visions of being a hunted animal running from poachers.",
	"PC gains a pet rock familiar.",
	"PC can speak with plants once per week. (equivalent to succeeding a Gather Information or Knowledge nature of 15 DC)",
	"PC's hands double in size, and can use weapons one size category larger than the PC with no penalties.",
	"PC becomes extremely trusting of a random base race.",
	"PC learns to brew diet healing potions. (Does not actually heal)",
	"PC's backpack disappears, and can just pull out items from behind their back, as long as they can carry it.",
	"PC can use and throw vegetables to cast bolts of magic missile. Each vegetable is one bolt. (treated as spell, not thrown object)",
	"PC switches eyes with the next creature with eyes they come into contact with. (Eyes will shrink/grow proportionally for all involved)",
	"PC grows a second head that has a separate personality.",
	"Any meal prepared by the PCs result in a gourmet lobster meal that, although looks delicious, doesn’t taste very good. (Regardless of the ingredients used)",
	"PC can not exist any further away than 50 ft. of a random party member.",
	"People with magic naturally distrust the PC.",
	"PC's bones become unbreakable. But will take damage normally.",
	"Whenever the PC receives a critical with a weapon, the weapon breaks. (after taking damage)",
	"PC's jaw splits in two, but can talk normally.",
	"PC is only seen as a silhouette.",
	"Every hour, PC has a 30% chance of falling asleep. PC can be woken up normally, or will otherwise sleep for 8 hours.",
	"PC lays an egg (regardless of species). (What kind is DMs choice.)",
	"When the PC leaves the ground, they become twice as heavy. (Take twice as much fall damage)",
	"PC learns to understand the next language they hear that they don’t currently know.",
	"PC's palms and fingers become immune to fire.",
	"It rains outdoors whenever the PC is sad.",
	"PC can use their index finger, and middle finger as a functional pair of scissors.",
	"PC is able to get reliable directions from snails. (They speak very quietly though.)",
	"Any number of hands will sprout from the PC’s body as long as there is another hand left to shake, shoulder to pat, etc.",
	"If an insect comes in contact with a PC, it's size becomes the same size category of the PC, and it becomes dire.",
	"The PC's eyes move together to become one big eye.",
	"PC remembers the night a wizard knocked them out, and turned them into a beautiful mermaid. It’s still fuzzy how they got to be what they are now.",
	"PC gains a Tortoise mount.",
	"PC recently took an inviolable vow but can’t quite remember it. (DMs choice)",
	"PC becomes a were-human. (even if they're human, they turn into a different human)",
	"PC comes down with a nasty infection from the Solanum disease. (Zombies!)",
	"2d8 of PC's teeth turn to gold. Can be sold 2 gp each. (but must yank them out first)",
	"PC believes everyone is an imposter of themselves.",
	"Roll again, the effect is twice as strong. (Twice as long, twice as much, etc.)",
	"Everything in the world becomes aware of who the PC is.",
	"PC gains a prehensile tongue that can extend out 5 ft.",
	"PC develops an intense fear of trees; they might be treants.",
	"PC can run up walls and other flat surfaces, but if they stop or change direction, they will fall.",
	"PC has a remarkable knack for teaching monkeys sign language.",
	"PC can use their own hands like a musical instrument. (Sounds a bit like a piano)",
	"Anything the PC pees on will forcibly align itself to magnetic north.",
	"PC will now make up any excuse to fuel their newfound collection of tiny animal figurines.",
	"PC can summon doors that when opened, lead to a random plane. They, however, cannot summon the doors when in a plane other than the material plane.",
	"At the start of every encounter the PC must declare whether or not they are willing to kill anyone.",
	"PC's bones can be played like a xylophone.",
	"Relatively shallow bodies of water split in a dry path whenever the PC walks through them.",
	"PC enjoys a good meal of brains. They also gain very small memories from the brains they consume, and can make a Knowledge brains check (+10 normal DC) instead of any normal knowledge check.",
	"PC's personal space collapses in on itself and implodes around the PC. After 1d3 days of recovery, the PC can no longer be crushed by any circumstance.",
	"PC suddenly recalls a past life where they were a wizard’s familiar.",
	"PC gives birth to a clutch of (DMs choice).",
	"PC can increase the length of any hair by pulling on it.",
	"PC becomes the central deity of a religious cult and gains followers. The cult can be based on anything the PC desires, (I.e. adventure, treasure, muffins...etc.)",
	"PC is only nourished by alcohol. (All other foods make them vomit. Will become drunk as normal.)",
	"PC's belly button can open to a 1 cubic foot pouch of holding.",
	"PC's breath is always a visible smoke. (can fill a room over time)",
	"PC can spend a full round action to succeed a DC 25 + HD of creature concentration check, to knock out one enemy.",
	"PC is invincible to all magic, but only while asleep.",
	"PC irrationally hates fungi. (stomps on them when they see them)",
	"Roll again, effect can be alchemized into a salve. (Ingredients are DMs choice)",
	"PC is knocked prone whenever they hear their name.",
	"A doppelganger of the PC is instantly created 5 ft away from them. The creature pays its humble respect and wanders off to see the world.",
	"Any shadow puppet the PC makes becomes a harmless living shadow of whatever it was.",
	"Whatever the PC says appears in words that float around their head for a little while.",
	"Roll again, the effect is twice as strong. (Twice as fast, twice as much, etc.)",
	"PC loses 50 lbs.",
	"PC can no longer answer a question truthfully.",
	"PC will never remember their name.",
	"PC’s pockets are now popular hangout spots for pocket gnomes.",
	"Any casted magic that affects the PC causes birds to swoop down and groom them. (Like a crocodile)",
	"PC's internal organs implode and compress into one super organ. PC looks only like skin and bones now. (is otherwise unaffected.)",
	"PC shoots out fireworks (works as dancing lights) whenever they're struck.",
	"PC gains a small doom cloud familiar.",
	"PC's blood becomes a nutritious snack for anyone lucky enough to taste it.",
	"PC gains a grog addiction, if they don't consume one once per week, they take -1 to all ability scores, increasing by one each day without grog.",
	"PC will now age backwards. (from how old they are now.)",
	"PC can no longer see a random party member",
	"PC's hair stands straight up as if electrically charged. It frizzes and discharges electricity. PC's handshake is shocking and static electricity sparks appear on the PC's body now and then. (Harmless, but can get annoying to be around.)",
	"PC can’t help but smile and giggle quietly to themselves at the misfortune of others.",
	"Roll again, the next living thing the PC touches also receives the affect.",
	"PC becomes irrationally prejudice of a random base race.",
	"PC and someone who looks exactly like the PC are suddenly aware of each other.",
	"During a full moon, the PC is accosted by undead tax collectors until dawn.",
	"Whenever the PC witnesses a crime, they are compelled to intervene. (Whether or not it's to bring the criminal to justice is up to them.)",
	"Within 5 ft of the PC is always 10 degrees hotter.",
	"PC's whistling attracts birds en masse.",
	"PC's left palm is considered a holy weapon, while they PC's right palm is considered an unholy weapon.",
	"PC finally remembers which one of their teeth was fake, and could be removed and opened to access a modest reserve of highly corrosive acid.",
	"PC cannot be killed by holy weapons.",
	"PC’s body becomes a kangaroo. (no stat change)",
	"PC has a grapevine constantly growing on them.",
	"PC’s eyes can function like laser pointers.",
	"PC is permanently dressed in a pristine Tuxedo. (Can wear armor over it)",
	"PC's blood becomes a flourescent light blue, and glows in the dark.",
	"Powerful spirits instruct the PC how to cook nice dinners in their sleep. It never turns out the same way when they try.",
	"PC can fly by sticking their thumbs in their armpits and flapping very hard.",
	"Everyone who first meets the PC says, “I’m so sorry” in a very concerned tone, although is not aware of saying it.",
	"PC is no longer liked, nor hated by anyone. (a reset)",
	"PC photographically remembers a map that leads to a questionably powerful artifact, with landmarks that may not exist in this realm.",
	"PC’s dreams are replaced with visions of being a wizard on the run from authorities, having discovered a terrible secret.",
	"PC's ghost is always viewing the PC's own actions in the third person.",
	"PC becomes a very dedicated carnivore. (Enemies look tasty)",
	"PC can use brooms to fly. (poor)",
	"PC is now affected by magnets. They are not themselves magnetic.",
	"Whenever a ranged attack misses the PC, it is considered they caught it with their teeth.",
	"Whenever the PC hears their name, they are briefly struck by inexplicable terror.",
	"PC can breathe in outer space.",
	"Roll a 1d12, at that time every 24 hours (pm), the PC is struck by lightning. (if outside. 1d6 damage to PC, 4d6 damage to anyone within 5ft)",
	"PC is able to sit on anyone’s head as long as the head is bald. (PC becomes as light as paper when doing so)",
	"PC will have dull pains on their body where ever they have struck killing blows to other creatures that go away after an extended rest. (Splitting headaches for splitting heads, stomach aches for stomach wounds)",
	"PC's hair becomes a mohawk that’s as hard as steel.",
	"PC's random body part becomes invincible. (Arms, teeth, etc; DMs choice.)",
	"PC can only be healthy via cannibalism. (Maybe even a civil one.)",
	"PC gets an amoeba familiar. (Will not multiply.)",
	"PC evaporates water when they touch it.",
	"A permanent image of the PC is left where they are standing right now.",
	"PC is afflicted with Porphyric Hemophelia. (Vampirism.)",
	"PC lays an egg (regardless of sex). (What kind is DMs choice.)",
	"If the PC pours water on the ground, it will become quicksand.",
	"PC learns to understand the next language they hear that they don’t currently know.",
	"PC sinks in ice as if it was quicksand.",
	"Whenever the PC enters a building, gravity immediately reverses orientation for them.",
	"PC's teeth become precious gems, and cannot be removed while the PC is alive.",
	"PC only cries blood. (Harmless)",
	"PC can bring down holy judgement on small spiders.",
	"PC does not have to touch objects to pick them up, but they must be in reach.",
	"PC can cure any mundane illness they’re afflicted with by taking a bath.",
	"PC remembers the night a wizard knocked them out, stole their gold, and forced them to eat their own shoes.",
	"PC only bleeds rainbows.",
	"PC sprouts a small, flaming wick atop of their head that can’t be put out. It burns brighter when they’re angry.",
	"PC constantly hears the playing of a guitar in the distance. (and could be drawn to it)",
	"If the PC is planted, they will grow into a tree that bears small fetus fruits that mature into babies of clones of the PC.",
	"A random party member becomes infatuated with the PC.",
	"PC grows a small leopard-print fuzz on their body.",
	"Roll again, the effect is twice as strong. (Twice as long, twice as much, etc.)",
	"PC can scry using a bald scalp.",
	"Whenever the PC is struck in combat, the weapon they were hit with combusts, dealing 1d4 force damage to anyone in 5 ft. and 1 point of continual fire damage for 1d4 rounds. The weapon does not break.",
	"PC's skin gains full body leopard print tattoos.",
	"PC suddenly realizes that they've actually been the person sitting next to them the whole time. The other person, embarrassed by this, offers to swap all their equipment and clothing.",
	"PC has a license for wild-geese chasing. (Ever been on a wild-goose chase?)",
	"PC learns recipe of random meal, gains the ingredients to prepare it, and will not be satisfied until they make the meal in a decent kitchen.",
	"PC has an extreme distaste for thieves and pirates.",
	"The grog pours out of the PC's mouth back into the mug, refusing to be drank by the PC. (needs new potion)",
	"PC's hair grows to touch the ground, and can be used as an arm.",
	"PC is pulled into the earth where they were standing until only their head shows, and must be dug up.",
	"PC does not sink in water.",
	"PC's hair bears fruit during harvest season.",
	"PC can become gaseous in direct sunlight. (Equipment can't)",
	"PC's internal organs become extremely unstable and explode. After 1d4 days of recovery, PC moves past the need for their organs.",
	"PC suddenly recalls a past life that was fairly normal until it ended abruptly as a sacrifice to a dark god. (It must not have worked, so the cult might try again.)",
	"PC's eyes become removable pearls, retain normal sight.",
	"PC is no longer able to sit or lay down.",
	"PC can swim up waterfalls.",
	"PC can inscribe markings into stone with their fingers.",
	"PC is poisoned. (DMs choice of poison)",
	"PC's eye sockets become pitch black. PC can see normally.",
	"Any facial hair the PC has becomes self-aware.",
	"PC can animate their own shoes to dance, but not while they're being worn.",
	"Any water drank by the PC is instantly purified.",
	"Roll again, PC becomes sick and the next effect becomes the main symptom. (DM may add any other symptoms as they like. 30% contagious to anyone who spends a day around the PC)",
	"PC becomes best friends with the current president of the United States.",
	"PC ages 100 years, and has 100 years added on to their natural life span.",
	"PC can walk on clouds. (Getting to them is a different problem)",
	"PC becomes unsure if they exist, often asking people if they really know who they are.",
	"Roll again, the effect is twice as strong. (Twice as fast, twice as much, etc.)",
	"PC gains a second personality. They can sort themselves out as they see fit.",
	"PC's body is covered with fire like an everburning torch. (No harm to PC)",
	"PC gains a voodoo doll of them self.",
	"PC realizes they have died centuries ago, and doesn’t know how they’re here now.",
	"Any casted magic that affects the PC causes a random limb to fall off. (Can be re-attached easily)",
	"PC turns to stone for 1d4 hours whenever someone makes eye contact with them.",
	"PC gains a permanent twitch.",
	"When PC walks over a spot where someone died, they instantly know where it was.",
	"The next thing the PC sits on will be able to fly. (poor)",
	"PC gains a grog addiction, if they don't consume one once per week, they take -1 to all ability scores, increasing by one each day without grog.",
	"PC can always cast the last spell that was cast upon them.",
	"PC's mouth can open to twice it's normal size.",
	"PC forgets their childhood, but would still recognize anyone important from it if they see them.",
	"PC can turn whatever they kill into small fist sized trophies.",
	"Roll again, the next living thing the PC touches also receives the effect.",
	"Whenever the PC falls they will always land on their face. (This includes jumping)",
	"PC's hair becomes a hedgehog familiar. Hair grows back at normal rate.",
	"When the PC's blood leaves the PC, it floats around like wax inside a lava lamp.",
	"PC turns invisible when eyes are closed. Does not affect clothing.",
	"PC no longer has a face, but can talk, eat, see, hear, and smell normally.",
	"Any animal the PC touches gains human-like intellect and speech as long as they're in contact.",
	"PC's feet become as flexible as hands. (+5 to climb when barefoot)",
	"Burning hot coals do not burn the inside of the PC's mouth or hands, and are actually quite the tasty snack.",
	"Whenever the PC takes damage, confetti erupts from their wound making a buzzing noise.",
	"PC's body becomes a gorilla. (no stat change)",
	"As long as the PC lives, a far off demon lord cannot return to life. (might be attacked by demon minions!)",
	"PC knows how wise any creature they encounter is.",
	"Any liquid the PC consumes becomes alcoholic. PC is also more immune to dehydration than most.",
	"PC's skeleton removes itself from the PC's body without killing them, and runs away. It takes 24 hours for a new one to grow back. The skeleton is the same alignment as the PC, but has no desire to become friends with them.",
	"PC is lectured by angelic figures in decency every night in their sleep.",
	"PC's skeleton glows a fluorescent red that's visible through their skin.",
	"PC cannot see the undead.",
	"PC moves and falls normally underwater, but only if completely submerged. (PC will still have to hold their breath.)",
	"PC's skin becomes soot black.",
	"PC's dreams are replaced with visions of being a beautiful mermaid viciously devouring the bodies of sailors.",
	"PC gains an aura of disagreement.",
	"PC can impregnate any species. The offspring will be the impregnated species.",
	"PC becomes a casual acquaintance with with a death god, and occasionally bumps into the god while they're on the job.",
	"Fruit sings if within 30 ft of the PC.",
	"Whenever a PC enters a building for the first time, it will eject them forcefully.",
	"PC becomes a were-tree.",
	"PC is able to spell and scribe any word they hear in any alphabet. (Whether they understand it or not is a different matter)",
	"PC can summon pillows at will, and they are extra fluffy. PC can summon at max one pillow per person in their party.",
	"PC can stop erupting volcanoes by pressing a finger to their mouth and shushing it.",
	"PC is now a particularly enjoyable stalking target for invisible stalkers. However, harming the PC would ruin the sport.",
	"Whenever the PC closes their eyes, they see the place where they used to live. It would be a shame if it burned down or something....hehehe...",
	"PC can move statues as though they were opposable.",
	"PC loses all hair on their body.",
	"PC can read books by flipping through them quickly.",
	"PC is burned by coming in contact with musical instruments.",
	"Whatever the PC touches has to agree with them, but can still physically resist them.",
	"PC is only nourished by the souls of who they slay. (All other foods make them vomit.)",
	"PC switches minds with the nearest dog.",
	"PC tastes like chocolate.",
	"PC learns to understand the next language they hear that they don’t currently know.",
	"Any plant the PC plants will grow in one day, but will never blossom or bear fruits or vegetables until it normally would anyway.",
	"PC attracts kobolds.",
	"PC learns one mundane song that they can play on any instrument.",
	"Fires whisper sweet nothings to the PC, encouraging them to succeed.",
	"Ethereal strings appear to be attached to the PC’s limbs and head, that extend upwards for a foot before trailing off.",
	"PC can no longer use outhouses to go to the bathroom.",
	"PC's soul cannot leave the material plane.",
	"PC remembers the night a wizard knocked them out, and stole their heart and lungs. (They’ve been replaced with magical wooden replicas)",
	"PC's tears are acidic. The PC is not burned by them.",
	"PC suffers intense pain whenever they enter a temple or church, regardless of the deity.",
	"PC will possess whatever kills them for 1d8+lvl days.",
	"The next enemy the PC meets will become friendly, but only to the PC.",
	"Every fruit the PC touches turns to glass.",
	"PC now has commitment issues. If they already had them before, they’re now more secure in their relationships.",
	"Roll again, the effect is twice as strong. (Twice as long, twice as much, etc.)",
	"PC will win every coin flip they do.",
	"PC can bring anything they've killed back to life. It will become permanently hostile to the PC regardless. (PC cannot gain experience this way)",
	"Any creature the PC kills evaporates. (Not equipment)",
	"Any change in HP of the PC floats away as numbers when it happens.",
	"PC is a champion pillow fighter. (but only with pillows)",
	"PC's urine can revive plant life.",
	"The PC is now burned by cold, and frostbitten by fire.",
	"PC now has an exceptional talent for making appropriately sized hats for small sized category animals or smaller.",
	"PC realizes they are an immortal soul inhabiting a temporary meat vessel that is slowly dying. What's worse is that they know nothing awaits them specifically after their body dies.",
	"PC can crack open any kind of nut or seed in their hand.",
	"PC's fingers grow twice as long.",
	"By rubbing their hands together fast enough, the PC can generate enough sparks to start a campfire.",
	"PC's hair becomes porcupine quills.",
	"PC seizes violently, becoming painfully statically charged. After 1d4 days of recovery, PC becomes a sustainable power source for any electrical equipment, regardless of if there is any.",
	"PC suddenly remembers a past life where they were a flightless bird that was experimented on, and criticized everything the experimenters did.",
	"PC gives birth to a brood of (DMs choice).",
	"PC glows a shade of gold in the presence of magic, and magical ore.",
	"PC eyes never close.",
	"PC can use carrots as daggers.",
	"PC's tongue becomes a harmless snake, and talk normally.",
	"PC's urine is extremely acidic. (does not harm PC)",
	"PC falls in love with the next enemy they see. (DMs choice if it is requited)",
	"Everytime the PC whistles, an eagle will swoop down and land on the PC's shoulder, and stare at whatever the PC stares at. It leaves if the PC enters combat.",
	"PC believes the next humanoid they see is their son and/or daughter and/or other.",
	"Roll again, effect can be transmitted through bodily fluids. (Urine, saliva, blood…)",
	"PC gains a political committee designed to elect the PC to a fictional political office.",
	"PC's skin turns red when it's hot, and blue when it's cold.",
	"PC is haunted by the ghost of everything they slay.",
	"It is always assumed that the PC killed their parents. (Whether or not it's true)",
	"Roll again, the effect is twice as strong. (Twice as fast, twice as much, etc.)",
	"PC's pockets has an unending supply of Cuban cigars. Cannot be sold. (Only given away graciously)",
	"PC is only able to enter rooms through dramatic actions.",
	"PC attracts insects of any size.",
	"PC always appears to be riddled with bullet holes. (Does not bleed from holes)",
	"Any casted magic that affects the PC causes an anvil to chain itself to the PC’s leg. (Break DC 17)",
	"The next wild mundane animal the PC sees, becomes domesticated to the PC.",
	"PC gains the profession Air Guitar skill. By strumming the air, the noises of a guitar are created. PC may attempt to dazzle and stun anyone within range of his voice with a wicked guitar solo as a full round action. Fortitude save DC 10 + PC's Air Guitar skill bonus.",
	"PC can no longer understand their racial language.",
	"PC's presence causes frost to form, but won't freeze anything.",
	"Scarecrows become the PC's worst nightmare.",
	"PC gains a new hairstyle every day.",
	"PC becomes attracted to themself.",
	"PC grows fur on their entire body.",
	"PC glows an eerie green for 3 seconds when their bellybuttons are pressed.",
	"Roll again, the next living thing the PC touches also receives the effect.",
	"PC can only communicate by saying their name over and over, and the party are the only ones who understand them. This includes past and future party members.",
	"No matter what the PC says, anyone who hears them will think they are attempting to seduce them.",
	"PC becomes intensely afraid of prostitutes.",
	"Whenever the PC witnesses a spell being cast, they are compelled to rate it on a scale of 1-10.",
	"PC becomes extremely flexible, to an inhuman point.",
	"PC gains a 6th finger on their left hand.",
	"PC can use weapons as musical instruments.",
	"PC will always land on their feet. Always.",
	"Doors attack the PC if they attempt to walk through them. (Wood: +3 1d6+2 smash attack. Metal: +3 2d6+3 smash attack. Stone: +2 2d8+4 smash attack.)",
	"PC's head becomes that of a velociraptor. (gains bite attack)",
	"PC has a powerful urge to punt anything in the tiny size category or smaller.",
	"PC gains opposable feet.",
	"PC's sweat releases an eerie blue smoke.",
	"PC's eyes become similar to an octopus, and can see underwater perfectly for 60 ft.",
	"PC makes their own god up and worships it. (It also exists due to it being worshiped.)",
	"PC’s pupils look like galaxies, with infinite detail.",
	"PC is no longer able to reproduce in any way.",
	"Magical items are drawn to the PC like a powerful magnet and activate once they hit the PC. (Reflex DC 15 to avoid setting them off)",
	"PC's nose glows blue when they pass near underground wells of water.",
	"PC's dreams are replaced with visions of being a virtuous ascetic nurse taking loving care of the sick, eventually dying of the sickness themselves.",
	"PC has a 10% chance of impregnating any creature with a normal grapple.",
	"PC becomes obsessively hygienic.",
	"PC can digest bones.",
	"PC grows animal horns. (DMs choice of moose, rams, etc.)",
	"Any mount ridden by the PC suffers no fatigue while they ride it.",
	"PC gains own shadow as familiar. (see shadow monster)",
	"PC becomes chronically pooped on by anything that flies.",
	"PC's nails fall off, and can be planted to grow any type of flower the PC wants. (Instantly)",
	"PC can shoot spider webs out from their fingertips when outside of combat.",
	"PC gains an excessively dramatic scar on their face.",
	"PC gains a permanent pair of glasses.",
	"PC can remove any curse, by only receiving it them self.",
	"PC can melt non-magical ice with their touch. They do not give off any extra heat.",
	"All liquids the PC consumes become caffeinated.",
	"PC can make a DC 15 Concentration check to summon the nearest bird, friendly or not.",
	"PC's feet becomes invincible, but they can still feel pain.",
	"PC becomes physically attracted to weapons.",
	"PC lays an egg (regardless of sex). (What kind is DMs choice.)",
	"PC becomes feral when their food is at stake.",
	"PC learns to understand the next language they hear that they don’t currently know.",
	"PC gains antennae on their head.",
	"When the PC is drunk, they can succeed a DC 17 fortitude save to release a stream of fire with a mighty burp. 10 ft line, 1d4 fire damage.",
	"PC becomes physically attracted to mundane animals.",
	"PC can make snowballs out of water.",
	"PC always wins at Rock, Paper, Scissors.",
	"PC is physically teleported to alternate planes in their sleep, but return to the material plane when they wake up.",
	"PC harbors an extreme distaste for sailors.",
	"PC remembers the night a wizard knocked them out, and stole their family’s magical sword heirloom.",
	"PC's voice of reason becomes an invincible squirrel that no one else can see.",
	"PC grows a ponytail of feathers all the colour of the rainbow. It makes for wonderful plumage.",
	"A bright round sphere looking object appears over the PC's head whenever they get an idea, or remember something.",
	"The next enemy the PC meets becomes directly related to the PC, 40% chance of being friendly.",
	"The entire party is pulled into the PC's dreams whenever the PC is asleep.",
	"PC's hair becomes smoke.",
	"Roll again, the effect is twice as strong. (Twice as long, twice as much, etc.)",
	"PC's hair becomes a chicken that insists on sitting on their head. The chicken is immune to damage, and does not leave the PC's head.",
	"Whenever it rains, the PC is always at the end of the rainbow.",
	"PC can only communicate with cat noises. (PC can talk normally to any feline)",
	"PC mistakes every woman they meet for the first time as their farming wife Charlotte.",
	"PC is able to dig graves with surprising amounts of gusto.",
	"PC can make a DC 15 Concentration check to summon the nearest bird, friendly or not.",
	"The PC's evil twin from a parallel dimension materializes next to them.",
	"PC gains a gambling addiction, and has magically bad luck.",
	"Every night, an intelligent woodchuck appears to tell the PC stories as they fall asleep.",
	"PC can use arrows without a bow. Instead they throw them. Use the stats of a short bow.",
	"Vines grow over the PC whenever they're asleep.",
	"PC permanently smells like a fresh ocean breeze. People might reminisce about their romantic experiences on beaches or boats.",
	"PC's head becomes invisible.",
	"A Boeing 747 commercial airliner crashes nearby. (DMs Choice as to what the plane's cargo was.)",
	"PC suddenly recalls a past life where they were an animal being worshiped in ancient times.",
	"Only the top half of the PC is visible.",
	"PC's touch leaves permanent black marks on any type of skin, except for their own. They also become great skin artists.",
	"PC can grow herbs on themselves harmlessly.",
	"Once per day, the PC can grant one mundane animal an INT score equal to their own, that goes away at midnight.",
	"PC's hair grows 3x quicker now.",
	"PC's fingers become a key ingredient to making a brew that can cure any and all diseases and poisons, magical or otherwise. PC is aware of the recipe. 1 finger per brew.",
	"PC grows 1d4 extra fingers on both of their hands.",
	"PC becomes extraordinarily attractive to trees.",
	"PC can swap places with one party member at-will.",
	"Roll again, PC gains the ability to cook the effect into a meal. (Ingredients are DMs choice)",
	"PC finds a dagger in their boot. (A +1 Dagger of Substantial Importance!)",
	"PC can only pee upon other people's legs.",
	"The next enemy the PC attacks becomes their reoccurring arch enemy that will plot dastardly schemes to destroy the PC and take over the world!",
	"PC's belly button can open to a 1 cubic foot pouch of holding.",
	"Roll again, the effect is twice as strong. (Twice as fast, twice as much, etc.)",
	"PC learns the spell Teach Esperanto, which will automatically teach Esperanto to the subject. Can cast at-will.",
	"PC gains an un-summonable glacier familiar.",
	"Next profanity used by PC becomes a living, vile entity.",
	"Any mundane creature the PC hugs becomes a plush doll version of itself for the duration the PC hugging it. (the animal cannot be harmed while plush)",
	"Any casted magic that affects the PC causes it to snow in the immediate area.",
	"Whatever the PC kills harmlessly explodes and splatters everywhere. (People, doors, etc.)",
	"Whenever the PC wakes up, they are in a coffin where they had went to sleep.",
	"The PC can only speak in their base language backwards.",
	"PC gets strange blisters that pop like bubble wrap on their arms. When they pop, they make different musical notes. They're not unsightly, just weird.",
	"PC gains a grog addiction, if they don't consume one once per week, they take -1 to all ability scores, increasing by one each day without grog.",
	"PC's joints are reversible.",
	"PC's hands can be unscrewed from their wrists.",
	"PC can remember their name, and that's about it.",
	"PC becomes a witch, and might encounter witch hunters.",
	"Roll again, the next living thing the PC touches also receives the effect.",
	"PC can use fruits as musical instruments.",
	"PC's hair turns white in the presence of magic. (If it's white to begin with, it turns a girly pink, complete with bows and ribbons.)",
	"PC's twin shows up, and is similar in every aspect except that their alignment is one step above or below the Characters.",
	"PC is sexually attracted to fire.",
	"PC is believed to be a doomsday weapon. (May be sought after by kings and nations.)",
	"When the PC sleeps, the grass either grows in 160 sq ft area around the PC, or the existing grass grows ten times it's normal size.",
	"PC's pockets spawn mundane playing cards one at a time.",
	"PC can cast a random cantrip spell at will.",
	"PC gains a key that can open their chest cavity harmlessly like a cabinet door.",
	"PC’s body turns into a troglodyte. (no stat change)",
	"PC can dance with bears, whether they're hostile or not. PC must make a Wisdom save DC 10 + bear's HD.",
	"A bottomless well is created next to the PC.",
	"Whatever object the PC sits on can be piloted. (Fly, 30 ft. poor.)",
	"When PC touches glass, they move through it like water. (Glass reforms.)",
	"PC now worships an Egyptian god.",
	"When the PC snaps, it sounds like a church bell. (As loud as a snap)",
	"PC gains an aura of incredulity. Everything the PC does seems incredulous.",
	"PC gains the knowledge of how to weaponize the grog, by imbuing it into a rod of wonder. The effects have a 50% chance of affecting the PC, or the target.",
	"PC's eyebrows grow twice their size and permanently cover the PC's eyes.",
	"PC’s dreams are replaced with visions of being an enormous force of pure evil slaughtering innocents.",
	"Whenever the PC is struck, a mundane creature will appear in their clothing. (rabbits, snakes, birds, etc.)",
	"PC is detected by Detect Undead.",
	"PC is constantly mistaken for an extremely evil demon.",
	"Wildlife brings the PC food periodically.",
	"PC didn’t actually exist prior to drinking this grog.",
	"PC's touch leaves permanent red blood splatter.",
	"PC can hear the thoughts of a random party member.",
	"PC has random manias of superb mathematical genius, but after 1d4 rounds, won't be able to understand what they had just said or done. During the mania, the PC's brain doubles harmlessly in size.",
	"PC is a were-construct.",
	"Magical effects cause the PC to emit the refreshing scent of peppermint.",
	"PC's weapons are permanently bound to them.",
	"An owlbear appears, runs toward the PC and hugs them for 1d4 rounds before disappearing. It automatically succeeds on its touch attack and all grapple checks. It attacks anyone who tries to harm the PC it is hugging. This happens at the same time everyday. Even if the bear is in combat, it will still disappear after 1d4 rounds.",
	"Whenever the PC sleeps, a bed of cabbages grows under them over night.",
	"It snows whenever the PC is sad.",
	"When the PC snaps their fingers, a apple appears before them. It's a normal apple. Max 1d4/lvl per day.",
	"A furious demon portal is opened up directly in front of the PC, and a monster of unspeakable horror named Howard suddenly sparks into existence.",
	"PC can teleport from the bottom of any freshwater lake to the bottom of any other freshwater lake.",
	"PC lays an egg (regardless of sex). (What kind is DMs choice.)",
	"PC's jaw becomes removable.",
	"PC learns to understand the next language they hear that they don’t currently know.",
	"PC receives mail from a long distance significant other periodically by Marvin the Mailman. (He's a mailman)",
	"PC is extremely prejudice against fruits and vegetables.",
	"PC gains an Easter Island head familiar. When it's summoned, it sits there and creeps everyone out.",
	"PC gains once per day use of a spell equal to Cha modifier. (Use modifier for DC)",
	"PC gains a grog addiction, if they don't consume one once per week, they take -1 to all ability scores, increasing by one each day without grog.",
	"PC can steal one prepared spell from grappled spell casters that doesn't exceed their Int modifier.",
	"PC's thumb turns greens, and can cause plants to grow at a rapid rate, but cannot exceed their normal size.",
	"PC remembers the night a wizard knocked them out, and sent back in time from (DMs choice of how far in the future).",
	"PC can remove their face like a mask.",
	"PC’s heart will never stop beating, even if removed.",
	"PC thinks any form of eating meat is a crime against nature.",
	"PC's mouth is stuck in a permanent smile.",
	"PC's right arm is interchangeable with any other creature's right arm. (PC can remove right arms harmlessly)",
	"PC grows an extra finger and toe on each hand and foot. (No effect if PC lacks hands and feet.)",
	"Roll again, the effect is twice as strong. (Twice as long, twice as much, etc.)",
	"PC can speak the language of the next mundane animal they meet.",
	"PC is able to shove their foot up any butt, regardless if it fits or not. It deals pride damage.",
	"PC only requires sleep 1d8 hours of sleep a night. (Re-roll every night)",
	"Anything the PC wears turns to wood permanently, but retains all stats.",
	"PC has an unusually good talent for trout tickling. (May be illegal in some areas.)",
	"PC knows the Int score of any creature they encounter.",
	"PC can use a baguette as a longsword.",
	"PC becomes addicted to casting the last spell they casted, and really enjoys casting it whenever they get the chance, or an excuse.",
	"PC is no longer able to get drunk.",
	"PC physically regresses to when they were a child, but retains all stats and abilities.",
	"PC can snap their fingers together and produce sparks like flint and steel would.",
	"PC gains a second heart, and is able to hold their breath for 5-6 minutes before suffocating.",
	"PC disappears and is replaced with a map to their location.",
	"PC spontaneously ages 10,000 years. After 1d6 days of recovery, PC is physically otherwise in normal health and stats, but is still 10,000 years older. Lifespan continues as normal.",
	"PC suddenly recalls a past life where they were a beautiful princess who lived an affluent, and uneventful life.",
	"PC gives birth to a nest of (DMs choice).",
	"PC gains insect like wings, and can fly. (poor)",
	"PC gains 5 ft of height, but is not considered a size category larger. Stats don't change.",
	"PC believes that all other races other than their own are aliens.",
	"PC can use and throw fruit to cast bolts of magic missile. Each fruit is one bolt. (treated as spell, not thrown object)",
	"Whenever the PC goes to the bathroom, small, harmless earthquakes hit the surrounding area.",
	"Everytime the PC sneezes, an exact duplicate of themselves appears at least 20 ft away from the PC for 1d4 hours. PC must designate a mundane allergen that makes them sneeze. (Certain flowers, dust, mold, animals, etc.)",
	"PC has a zipper on the front of their chest that they can unzip and show off the inside of their torso.",
	"The next time the PC dies, they are resurrected as the race that killed them.",
	"Roll again, effect can be bestowed through a ritual the PC suddenly learns. (Material components are DMs choice)",
	"PC's shadow smokes as if it's on fire. (Not good to stay in enclosed spaces)",
	"Any statue resembling an animal that is within 30 ft of the PC is animated. If it goes beyond 30 ft, it ceases to be animated.",
	"PC can use wildlife as weapons.",
	"PC harmlessly but constantly bleeds from every orifice they have.",
	"Roll again, the effect is twice as strong. (Twice as fast, twice as much, etc.)",
	"PC's voice drops an octave and echoes no matter what.",
	"PC gains cat pupils, whiskers, and fur. (No low-light vision is gained, PC might tend to purr)",
	"PC's skin becomes translucent, and observers are able to see tiny fish swimming around inside of the PC.",
	"PC gains a spirit animal that appears whenever the PC is within 15 ft of fire. (DM’s Choice)",
	"Any casted magic that affects the PC causes plant life to over grow in the immediate area.",
	"PC's tears turn into jellybeans.",
	"All fire that burns within 30 ft. of the PC turns the colour of their choice.",
	"Any object the PC successfully breaks bursts into flower petals.",
	"PC gains 100 lbs.",
	"PC gains a grog addiction, if they don't consume one once per week, they take -1 to all ability scores, increasing by one each day without grog.",
	"PC knows the market value of any humanoid as a slave that they see.",
	"PC attracts floating candles.",
	"PC's eyes turn purple and gains an aura of purple. Anyone who is within 5 ft of the PC, including the PC, only sees in shades of purple.",
	"Everytime the PC attacks a mundane animal, a second one appears next to it.",
	"Roll again, the next living thing the PC touches also receives the effect.",
	"Any fruit the PC touches becomes dried and preserved.",
	"PC gains very dramatic looking battle scars that resemble almost every conceivable weapon known.",
	"PC becomes a ghost when they are in the rain.",
	"PC learns how to knit. Their knitted products are as tough as leather armor.",
	"For 1 minute, the PC is flung into a fit of hysteria where they are convinced that they are nothing but constructs in a game played by unseen beings who determine their every move. Afterwards, this experience stays with them forever.",
	"PC gains 1d4 more eyes.",
	"A talking rainbow unicorn offers to be the PC's steed. (Unicorn is Neutral Good)",
	"PC's blood can dissolve metal.",
	"Whenever the PC is left alone in a building, the building burns down.",
	"PC’s body turns into a medium-sized praying mantis. (no stat change)",
	"PC can pick up flames in their hands. (like, scooping up fire and throwing it.)",
	"When the PC dies, their ghost will haunt the party forever.",
	"PC gains a pair of sunglasses that when worn, they become 'too cool' for whatever action is decided. Does not effect hostilities.",
	"PC cannot die in their sleep.",
	"PC is now worshiped by a dying race of frog people.",
	"PC's hands never leave their sleeves. (PC also permanently wears long sleeve shirts.)",
	"PC becomes aware of a certain group of people who've managed to travel back in time. (No one in particular, it's DMs choice really)",
	"With 10 minutes of searching, the PC can find random dinosaur plushies hidden in the environment. They're worthless, but they have strange sentimental value.",
	"Whatever the PC is sitting on right now becomes their property.",
	"PC’s dreams are replaced with visions of an ancient temple where a magic artifact is sealed.",
	"Whenever the PC hears their name, a random flower sprouts somewhere on their person.",
	"PC's presence causes vegetables within 30 ft. to sing.",
	"PC gets accepted into the University of their choice.",
	"PC's left arms swaps with the last humanoid they touched.",
	"PC finds a compelling but incomprehensible magical tome in their inventory.",
	"PC has a giant round hole in their chest. (Harmless)",
	"PC's footsteps sound as though they were 3 size categories larger.",
	"PC gains a locked bulletproof briefcase that's permanently chained to their left wrist. (Contains some very powerful information, too bad no known locksmith can open it)",
	"PC's voice becomes completely different depending on what language they're speaking.",
	"Magical effects cause the PC to emit a pungent scent of the sea.",
	"PC becomes a were-zombie. (If already a zombie, they become were-alive.)",
	"PC now feels the need to route out the communists.",
	"PC is now permanently afflicted with glitter.",
	"PC will always smell like freshly baked cookies. Might attract wildlife.",
	"PC gains a permanent smiley face button on their shoulder.",
	"PC is cloned, but doesn't know where the clone is.",
	"PC goes down one size category. (With no Ability Score change)",
	"PC lays an egg. (What kind is DMs choice.)",
	"PC gains very well defined and shiny muscles, and can show them off as a free action.",
	"PC learns to understand the next language they hear that they don’t currently know.",
	"PC grows a small unicorn horn that glistens in the sunlight. (Cannot attack with it, too small)",
	"PC's feet attract snakes. 10% chance of being poisonous.",
	"Whatever the PC kills becomes a tombstone.",
	"PC gains once per day use of a spell equal to Cha modifier. (Use modifier for DC)",
	"PC gains a grog addiction, if they don't consume one once per week, they take -1 to all ability scores, increasing by one each day without grog.",
	"PC attracts suspicious little red glowing dots.",
	"PC gains a butterfly familiar. (The PC doesn't know it's their familiar though)",
	"PC remembers the night a wizard knocked them out, polymorphed them, and stole their original identity.",
	"If the PC falls in love (truly), then whoever they love will mysteriously and spontaneously combust the next day.",
	"To only the PC, puddles are always 10 ft. deep.",
	"PC gains a pencil-thin mustache, a thick British accent, and an urge to lift one eyebrow.",
	"Spectacular lightning strikes flares overhead when the PC's name is said.",
	"PC looks like a ghost in the moonlight.",
	"PC can make a normal swim check to swim through the ground. (Like getting to underground places) Failing the check results in entombment.",
	"Roll again, the effect is twice as strong. (Twice as long, twice as much, etc.)",
	"PC's whistle sounds like a contrabass saxophone.",
	"PC can boils small quantities of water by staring at it for 1d6 rounds.",
	"PC invents the Harpmonicsicordiphone.",
	"PC breathes out harmless lightning clouds. Can shock/distract people.",
	"PC has what it takes to be an Olympic-level vagrant.",
	"PC goes down one size category.",
	"When PC is submerged in the ocean, they transform into a blue whale. They must beach themselves to turn back. Their equipment expands to fit them.",
	"PC's hair becomes as strong as steel.",
	"PC no longer has a midsection. (Still eats normally)",
	"At the start of every encounter the PC must succeed a DC 10 Will save or roll for a new alignment.",
	"PC gains their own brain as their familiar. It can exist harmlessly outside of their body.",
	"PC can breathe beneath only 5 ft. of water.",
	"PC attracts whatever they are afraid of.",
	"PC briefly glimpses into the chaotic omnicosm that underlies all reality, and gains some sort of inexplicable and incomprehensible wisdom as to the fundamental mechanisms of their existence.",
	"PC suddenly recalls a past life where they were a cat on a boat that had a mysterious cargo.",
	"PC petrifies all grass they walk on.",
	"Whenever the PC leaves the ground, they become as heavy as paper. (Will fall normally though)",
	"PC becomes intensely afraid of penguins. (Sphenisciphobia) (Penguins are not unknown to stalk people)",
	"PC is nourished by charcoal instead of food. (Food harmlessly burns in their mouth while they chew, can not be used to bite.)",
	"PC can pull their hand off, revealing a dagger attached outwards from their wrist. Their hand functions normally when sheathed and not.",
	"PC can make a DC 15 Concentration check to summon the nearest bird, friendly or not.",
	"Whenever the PC makes a fist, they become round spheres of steel. (Dmg 1d6 + Str.)",
	"PC's tears are a fine vintage white wine.",
	"Whenever the PC takes damage, they must make a DC 13 Fortitude save or fall unconscious for 1d4 rounds.",
	"Roll again, effect can be smithed into a weapon that imbues the effect onto whomever holds it. (Cheap materials, as well as a smith, are DMs choice)",
	"PC is surrounded constantly by a personal 'bubble'. When it pops, it takes 2 rounds to reform.",
	"Sand perpetually pours out of the PC's eye sockets when their eyes are open. PC sees normally.",
	"A random limb becomes only the functioning skeleton of it.",
	"PC can summon small versions of themselves that sit on their shoulders and argue with each other or other people.",
	"Roll again, the effect is twice as strong. (Twice as fast, twice as much, etc.)",
	"PC's burp becomes the mating call of unicorns.",
	"PC becomes discretely stalked by a garden gnome.",
	"PC's nose bleeds when anything venereal is discussed.",
	"Doors will always hit the PC on the ass on the way out. (Tougher doors hit harder)",
	"Any casted magic that affects the PC causes water nearby to become holy/unholy. (Depending on alignment)",
	"PC is no longer related to anyone.",
	"PC's blood harmlessly becomes sand.",
	"PC's presence causes animals within 30 ft. to sing.",
	"Once per day, the PC becomes encased in a layer of brittle stone.",
	"PC can weave impressive wicker objects, but only while completely submerged in water.",
	"Whenever the PC makes a joke, a laugh track plays in the background.",
	"PC's HP is instantly (and only) reduced to 1 if struck with an unholy weapon, but is healed by holy weapons.",
	"PC perspires rainbows.",
	"Any door the PC tries to open instantly locks itself. (Can still be picked)",
	"Roll again, the next living thing the PC touches also receives the effect.",
	"Whenever the PC falls asleep, their clothes fly away and migrate south for the winter.",
	"Anything the PC kills is personally escorted to hell by the Grim Reaper.",
	"PC is now healed by mushrooms. (1d4 + Con modifier per shroom)",
	"PC sprouts a singing venus fly trap on their shoulder that sings when the PC is happy.",
	"PC can send messages to anyone they've met by speaking into a frog or toad.",
	"As long as the PC pets a creature, it is able to speak it’s mind.",
	"PC gains 3 fox tails.",
	"PC's blood becomes a blood elemental, and is very comfortable being inside the PC's body. Blood that leaves the PC's body will make its way back into the PC's wounds.",
	"PC's butt dispenses 10 ft. of rope per day.",
	"PC’s body is permanently covered in mummy wraps. (no stat change, preserve body upon death)",
	"PC can skip themselves off of water (10 ft.) with a DC 5 jump check, with each successive skip increasing the DC by 5.",
	"PC sings manly songs whenever they're in combat.",
	"PC can now focus hard enough to become a sword, but this does not include their clothing or equipment.",
	"A random party member can now hear the PC's thoughts.",
	"PC is now idolized by a dying race of flower fairies.",
	"Anything the PC kills becomes preserved forever.",
	"If the PC touches a plant, it glows in the dark.",
	"PC's right index finger (or equivalent) gives off a harmless red laser.",
	"The souls of whoever the PC kills linger around them in the form of small heatless balls of purple-ish fire.",
	"PC’s dreams are replaced with visions of being the last priest in a forgotten order.",
	"PC gains a wombat for a mount.",
	"Every time the PC is struck on the head with any force, they change to the opposite alignment.",
	"PC's sweat becomes a very lovely smelling perfume, reminiscent of the favorite memory of anyone who smells it.",
	"PC's body hair is replaced with 3 leafed clovers. (Can be searcched for a four leafed)",
	"PC comes upon an invincible key that explodes anytime it is inserted into a lock.",
	"PC no longer blinks. Anyone who stares too long into the PC's eyes will hear a Gregorian choir chanting louder and louder before passing out.",
	"PC can run across water, but if they stop or change direction, they sink.",
	"PC's eyes are permanently covered with shadow, and are impossible to see under any light.",
	"PC chooses an obscure food product. They become professionals in cooking it.",
	"PC’s mandible can be removed and thrown as a boomerang.",
	"PC learns how to foster squirmles, a tiny lovable but mischievous race of fuzzy worm things.",
	"PC now has green, copper based blood.",
	"PC does not cast a shadow.",
	"A 60 ft wide snowstorm surrounds the PC for 1d4 hours every 2 days at noon.",
	"PC is unable to talk around the undead.",
	"Any weapon the PC holds is able to talk, and is normally very eager to do so.",
	"PC learns recipe of random meal, gains the ingredients to prepare it, and will not be satisfied until they make the meal in a decent kitchen.",
	"PC finds their own baby. (What kind is DMs choice.)",
	"PC gains a grand piano familiar. (Summonable at-will, at ground level)",
	"PC learns to understand the next language they hear that they don’t currently know.",
	"People with magic are physically attracted to the PC.",
	"PC becomes a living statue in the light of a full moon.",
	"Continual fog empties out of the PC's ankles filling a 30 ft radius. 1 ft high.",
	"PC gains once per day use of a spell equal to Cha modifier. (Use modifier for DC)",
	"PC gains a grog addiction, if they don't consume one once per week, they take -1 to all ability scores, increasing by one each day without grog.",
	"PC can use wildlife as musical instruments.",
	"PC can chop non-magical wood with their bare hands.",
	"PC remembers the night a wizard knocked them out, and stole their brain. (It’s been replaced with a magical wooden replica)",
	"PC gains 1d4 different voices that they can use interchangeably at-will.",
	"Mysterious runes are visible on the PC’s skin in the moonlight.",
	"PC becomes unnaturally fascinated with piercing their body piercings. (Can be replaced with magical ones)",
	"PC's head can rotate 360 degrees around.",
	"PC's brain becomes clockwork, and must be wound every 24 hours. Otherwise PC's INT drops to 0 until it's wound again.",
	"PC can make a DC 15 fortitude check to cough up one lung. It grows back after 24 hours, until then, PC cannot run.",
	"Roll again, the effect is twice as strong. (Twice as long, twice as much, etc.)",
	"Whenever the PC goes to sleep, they are kidnapped for the amount of time they rest. After which they are returned to the exact same spot, fully rested.",
	"Around the PC, the moon appears to be constantly full at night.",
	"PC hiccups bubbles. 2d4 bubbles per round for 2d4 rounds when caught flatfooted (or surprised).",
	"PC can be nourished by awkward moments.",
	"PC is a professionally bad dancer.",
	"PC flips a coin to decide whether or not they should tell the truth. (Heads = truth, Tails = false)",
	"PC can only read and write languages they do not know how to speak.",
	"PC becomes addicted to casting the last spell they casted, and really enjoys casting it whenever they get the chance, or an excuse.",
	"PC occasionally and inexplicably becomes in possession of random people's underwear.",
	"At the start of every encounter the PC must succeed a DC 10 Will save or roll for a new alignment.",
	"PC can sheath any type of sword in their forearm, and not be hindered in their movement.",
	"PC gains a purple thumb that causes non-magical plants to whither and die.",
	"As long as the PC has throwing knives, they can inexplicably pull them out of any where on their person.",
	"PC fades into an existential quandary filled with angst and self-loathing. After 1d8 days of recovery, they will gain a perspective of persistent optimism, because nothing will be as a bad as that.",
	"PC suddenly feels as though they are being remembered by a future life.",
	"PC gives birth to a litter of (DMs choice).",
	"PC's head is removable. It will remain active, as well as the body.",
	"PC gains a talking tattoo. Roll for tattoo's alignment.",
	"PC is able to lick an enemy to paralyze them for 1d6 rounds. Fortitude save DC 10 + PC's level negates.",
	"Everytime the PC dances, a natural disaster happens somewhere. (2% chance it happens right where the PC is)",
	"PC's consciousness swaps with a future incarnation from the 21st century. (No stat change)",
	"PC can now directly communicate with their god, but cannot get help from them.",
	"PC can identify any substance by ingesting it.",
	"PC is burned by water, except when they drink it.",
	"Roll again, the effect spreads to casters that cast magic on the PC. (Lasts 1 day/PC level)",
	"From now on, whenever the PC meets a new person, the new person will only ever be able to dream about the PC.",
	"Whatever the PC guesses will always be correct, but no one will ever believe them.",
	"PC is able to be used as a great club by other characters in the same size category. PC takes half damage minus their armor bonus.",
	"PC becomes a dragon in a human form with the same stats as they had before, but has forgotten how to polymorph.",
	"Roll again, the effect is thrice as strong. (Thrice as fast, thrice as much, etc.)",
	"It's now impossible to describe the PC's physical appearance, leaving people exasperated if they try.",
	"PC is made of felt. (But takes all damage normally)",
	"PC can use animal husbandry to allow any two creatures to birth hybrid offspring.",
	"PC grows 1d10 new and mysterious organs in their abdomen.",
	"Any casted magic that affects the PC causes all nearby wildlife to double in size.",
	"PC's singing attracts hostile creatures.",
	"If the PC opens a closet, there will always be a dead body in it.",
	"PC's middle name becomes 'Danger'.",
	"PC can shoot anything with a bow that they can lift.",
	"PC gets a +1 to all checks while the sun is out, and a -1 to all checks while the sun is down.",
	"Whoever makes eye contact with the PC cannot help but laugh.",
	"PC cannot go to sleep while above ground.",
	"PC can plane shift once per day, and move 5 spaces before coming back to the material plane. They have a 60% chance of bringing something back with them, and a 20% chance of it being friendly.",
	"PC is severely allergic to intimacy. (Symptoms include sneezing, nasal congestion, and inflammation of the eyes.)",
	"Roll again, the next living thing the PC touches also receives the effect.",
	"PC is physically moved to tears whenever they part with any of their money.",
	"PC is abducted by aliens, probed, surgically implanted with an unknown alien device, and is put back in the same spot about 10 minutes later.",
	"Beneath the PC's skin, they become entirely clockwork. They take damage and die normally, and don't feel any different.",
	"Whenever the PC kills a creature, they give the PC a recipe of a mixed cocktail drink that highlights their life.",
	"PC will randomly trip and crash into party members of the opposite sex. Ending up on top of each other with one of them holding the other's breast. (At DMs discretion)",
	"Once per day, the PC can summon a stream of 600 butterflies to swarm themself for 1d4 rounds, blinding everyone including the PC within 40 ft. until they're dispersed.",
	"PC learns every recipe there is to cooking and serving the slain bodies of their enemies.",
	"PC can cure any disease, remove any poison, or remove any condition by being afflicted by the condition themselves.",
	"For any sneak attempts, the PC can instead say, 'You can't see me, I'm hiding. to anyone who might see them for the same effect.",
	"PC’s body turns into a medium sized minotaur. (no stat change)",
	"PC becomes a dimensional rift that alternate realities can enter through.",
	"PC is possessed by a demon that acts the exact same way as the PC did beforehand. The demon is detected by Detect Evil, but is the same alignment of the PC.",
	"PC becomes irresistibly cute, but only while on fire.",
	"Once per day, the PC can vomit freshly caught fish.",
	"PC makes their own god up and worships it. (It also exists due to it being worshiped.)",
	"All Gods abandoned the PC.",
	"PC's consciousness visits the modern era in their dreams, by taking the body of a future incarnation.",
	"PC is abducted by aliens for 1d4 days. (DMs choice of what happens)",
	"PC has a 30 ft aura of a full-moon. (Affects were-creatures)",
	"PC’s dreams are replaced with visions of incomprehensibly horrendous Lovecraftian horror-terrors from beyond.",
	"The Aurora Borealis are always above the PC at night.",
	"PC is now a werewolf.",
	"The PC's heart becomes the perfect phylactery for anyone aspiring to become a lich.",
	"The PC is considered dead for the duration they sleep. When they wake up, they are resurrected.",
	"PC finds a notebook detailing how they were built in a lab.",
	"PC is not comfortable sleeping unless they're hanging upside down from their feet.",
	"PC becomes married to the sea. If PC already has a spouse, they will kill them and become a sailor. (Doesn't leave the party)",
	"PC goes up one size category. (With no Ability Score change)",
	"PC can make a DC 17 Will Save to grow a fabulous and amazing mustache.",
	"PC is immune to all compulsory effects, but only if they’re completely naked and not carrying anything.",
	"PC can make a DC 13 Strength check to punch into the ground and pull out any type of vegetable.",
	"PC's presence causes bubbles to explode. 2d4 fire damage each.",
	"PC ceases to age, but will die at the end of their lifespan.",
	"Whenever the PC is cold or freezing, they become undead. When they are warmed up again, they come back to life.",
	"No ship can float while the PC is on board, however, they can be sailed underwater.",
	"PC becomes aware of a contract they have with the mole people to defile any gardens they happen to pass by. (Farms don't count, petunia bushes do)",
	"PC's long lost fraternal twin will visit the PC soon.",
	"PC lays an egg (regardless of sex). (What kind is DMs choice.)",
	"PC degenerates into an earlier form of their race. (No stat change)",
	"PC gains a random language.",
	"PC can no longer speak unless they are touching someone, and can only speak in the languages of the person they are touching.",
	"PC becomes permanently drunk.",
	"PC has an aura of badass-itude.",
	"PC gains once per day use of a spell equal to Cha modifier. (Use modifier for DC)",
	"Every time the PC is alone, they always have a chance of finding their own dead body that who’s cause of death is different each time. (The bodies do not have equipment, only the PC’s undergarments)",
	"Whatever the PC kills will come back to life as a zombie immediately. 50% of being friendly. All creatures die permanently at midnight the day they were raised.",
	"PC ascends to a higher dimension, learns how to exist in this dimension, and then instantly pops back into the material plane with no memory of the event. (May have made friends, or enemies in their time)",
	"PC remembers that they were once a criminally deranged wizard who had knocked themselves out and wiped their own mind of everything they had done.",
	"The name and face of everyone the PC kills is automatically tattooed to their skin when they die.",
	"Tomorrow, PC will save the life of whom fate has decreed must die.",
	"All of the PC's criticals and fumbles are twice as effective as they normally were.",
	"PC explosively sheds their skin once a month, starting now. (2d6 force/fire damage, 10 ft. radius)",
	"PC's urine morphs trees into treants. They won't be happy you peed on them.",
	"PC can swallow ores and defecate the refined material.",
	"Roll again, the effect is thrice as strong. (Thrice as long, thrice as much, etc.)",
	"PC can make a DC 10 + Animal's HD Will Save to make mundane animals fall unconscious.",
	"PC reproduces by budding. (Still needs a mate)",
	"PC can summon a magical gong at will and hit it for whatever reason they feel like. The gong doesn't do anything because it's a gong.",
	"PC's only mode of transportation is the moon walk.",
	"PC receives their diploma in Dilly-Dallying from the College of Substantial Whimsy.",
	"PC has an hardcore aura. Everything they do is pretty hardcore.",
	"The absolute most crazy and absurd things will happen to the party, but only when the PC isn't around.",
	"PC can store normal sized ships in bottles.",
	"PC is detected by any Detect spell.",
	"Nothing happens. (What are the odds?)",
	"The PC is aware that the next time they die, they bursts into flames destroying all flammable gear and is resurrected.",
	"PC becomes best friends with an epic wizard that only ever comes around to ask for loans of money to fund their crazy ideas.",
	"Every time the PC levels up, they have a choice of switching to a different class of the new total level",
	"PC briefly glimpses into the chaotic omnicosm that underlies all reality. After 1d10 days of recovery, PC gains some sort of inexplicable and incomprehensible wisdom as to the fundamental mechanisms of their existence.",
	"1000/0	PC is divided by zero.",
]